import CreateRoomModal from '@/components/CreateRoomModal';
import { OptionO, OptionX } from '@/components/options';
import RoomList from '@/components/RoomList';
import { Room } from '@/models/Room';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { io } from "socket.io-client";

const size = 72;
const gap = 4;
const maxSize = size * 3 + gap * 2;

export default function Home() {
  const [points, setPoints] = useState<number[]>(Array(9).fill(0));
  const [option, setOption] = useState<"x" | "o">("x");
  const handleClick = async (i: number) => {
    // send points
    const newPoints = [...points];
    newPoints[i] = i % 2 ? 1 : -1;

    const fetchPromise = await fetch('/api/xox', {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        points: newPoints
      })
    });
  };

  useEffect((): any => {
    const socket = io(`http://localhost:3000`, {
      path: "/api/socket"
    });

    socket.on("connect", () => {
      console.log("SOCKET CONNECTED!", socket.id);
    });

    socket.on("points", (points: number[]) => {
      console.log("SOCKET POINTS!", points);
      setPoints(points);
    });

    if (socket) return () => socket.disconnect();
  }, []);

  const rooms: Room[] = [
    {
      id: "1",
      name: "I am a room",
      password: "1234",
      players: [
        {
          id: "1",
          option: "x"
        },
        {
          id: "2",
          option: "o"
        }
      ],
      points: Array(9).fill(0),
    },
    {
      id: "12",
      name: "Lets play :)",
      password: "1234",
      players: [
        {
          id: "1",
          option: "x"
        },
        {
          id: "2",
          option: "o"
        }
      ],
      points: Array(9).fill(0),
    }
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-full flex2 flex-col justify-center items-center gap-10 bg-gray-800'>
        {/* <button
          type="button"
          className="inline-flex justify-center rounded-md border border-transparent bg-green-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm"
          onClick={() => setIsOpenCreateRoomModal(true)}
        >
          Oda Oluştur
        </button>
        <CreateRoomModal open={isOpenCreateRoomModal} onClose={() => setIsOpenCreateRoomModal(false)} />
        <div className="grid grid-cols-3 bg-teal-400" style={{ maxWidth: maxSize, gap }}>
          {points.map((point, i) => (
            <div
              className="bg-gray-800 flex justify-center items-center"
              style={{ width: size, height: size }}
              onClick={() => handleClick(i)}
            >
              {point === 1 ? <OptionX /> : point === -1 ? <OptionO /> : null}
            </div>
          ))}
        </div> */}
        <RoomList rooms={rooms} />
      </main>
    </>
  )
}
